### ISSUE TITLE
Substrate compatibility

### ISSUE THREAD

**Issue by ascjones** [paritytech/scale-info#36]
As part of a proof-of-concept to utilize `scale-info` in substrate, this issue will track all the changes in this crate in order to make it work.

- [x] Add informational field type name #30
- [x] Consolidate common prelude for std and no_std and usage #33
- [x] Derive TypeInfo for fields with associated types without bounds #20 
- [x] Optional serde feature #34 
- [x] Parameterize CompactForm String for optional SCALE impl #35
- [x] Use PortableRegistry for encoding and serializing #40
- [x] Add a `compact` flag to `Field` #42
- [ ] Handle more SCALE attributes: skip, index #44 

For reference, all the above mentioned PRs are integrated into the https://github.com/paritytech/scale-info/compare/aj-substrate branch, which is the working branch I am using from my substrate branch PoC https://github.com/paritytech/substrate/compare/aj-metadata-vnext

**Comment by ascjones** [comment]
Superseded by #89
