### ISSUE TITLE
Tracking issue for 1.0

### ISSUE THREAD

**Issue by ascjones** [paritytech/scale-info#89]
Tracking issue for what we definitely need to cut a `1.0` release for substrate, which we should aim for before this makes its way into any mainnet chains. Note that we may do an intermediate release for the substrate PR https://github.com/paritytech/substrate/pull/8615, leaving the door open for any breaking changes after that PR is merged, but before it is deployed anywhere.

- [x] Enum indices #80
- [x] Doc comments #87
- [x] Compact type bounds #83
- [x] 0 based type lookup ids #90
- [ ] ~~Handle Box types #82~~ **Edit: can go in a `1.x` release**
- [x] Skip type params #95
- [x] Potentially reconsider `TypeInfo` bound on the `T` in `PhantomData` to remove the requirement for some unnecessary(?) `TypeInfo` bounds in https://github.com/paritytech/substrate/pull/8615
- [ ] ~~Naming of things, are we happy with naming of types/concepts etc. before we lock down for `1.0`?~~ **Edit: naming stays the same for 1.0**
  - [ ] Rename `Composite` and `Variant` type defs #93
